[vader-nvim-win]
    command = "make"
    args = ['test']
    isBackground = false
[vader-nvim-win.options.env]
    VIM_BIN = 'nvim'
    VIM_Es = "--headless"
[vader-nvim-wsl]
    command = "make"
    args = ['test']
    isBackground = false
[vader-nvim-wsl.options.env]
    VIM_BIN = 'wsl -e nvim'
    VIM_Es = "--headless"
[vader-nvim-050]
    command = "make"
    args = ['test']
    isBackground = false
[vader-nvim-050.options.env]
    VIM_BIN = 'D:\Neovim\v0.5.0\bin\nvim.exe'
    VIM_Es = "--headless"
    VIM = 'D:\Neovim\v0.5.0'
[vader-nvim-072]
    command = "make"
    args = ['test']
    isBackground = false
[vader-nvim-072.options.env]
    VIM_BIN = 'D:\Neovim\v0.7.2\bin\nvim.exe'
    VIM_Es = "--headless"
    VIM = 'D:\Neovim\v0.7.2'
[vader-nvim-080]
    command = "make"
    args = ['test']
    isBackground = false
[vader-nvim-080.options.env]
    VIM_BIN = 'D:\Neovim\v0.8.0\bin\nvim.exe'
    VIM_Es = "--headless"
    VIM = 'D:\Neovim\v0.8.0'
# vim 7.4.1185 
[vader-vim-741185]
    command = "make"
    args = ['test']
    isBackground = false
[vader-vim-741185.options.env]
    VIM_BIN = 'D:\Vim\gvim_7.4.1185_x64\vim.exe'
    VIM_Es = "-Es"
    VIM = 'D:\Vim\gvim_7.4.1185_x64'
    VIMRUNTIME = 'D:\Vim\gvim_7.4.1185_x64'
[vader-vim-741185-buf]
    command = 'D:\Vim\gvim_7.4.1185_x64\vim.exe'
    args = ['-Nu', 'test/vimrc', '-c', 'Vader! ${relativeFile}']
    isBackground = false
[vader-vim-741185-buf.options.env]
    VIM = 'D:\Vim\gvim_7.4.1185_x64'
    VIMRUNTIME = 'D:\Vim\gvim_7.4.1185_x64'
# vim 7.4.1689
[vader-vim-741689]
    command = "make"
    args = ['test']
    isBackground = false
[vader-vim-741689.options.env]
    VIM_BIN = 'D:\Vim\gvim_7.4.1689_x64\vim.exe'
    VIM_Es = "-Es"
    VIM = 'D:\Vim\gvim_7.4.1689_x64'
    VIMRUNTIME = 'D:\Vim\gvim_7.4.1689_x64'
[vader-vim-741689-buf]
    command = 'D:\Vim\gvim_7.4.1689_x64\vim.exe'
    args = ['-Nu', 'test/vimrc', '-c', 'Vader! ${relativeFile}']
    isBackground = false
[vader-vim-741689-buf.options.env]
    VIM = 'D:\Vim\gvim_7.4.1689_x64'
    VIMRUNTIME = 'D:\Vim\gvim_7.4.1689_x64'
# vim 8.0.0027
[vader-vim-800027]
    command = "make"
    args = ['test']
    isBackground = false
[vader-vim-800027.options.env]
    VIM_BIN = 'D:\Vim\gvim_8.0.0027_x64\vim.exe'
    VIM_Es = "-Es"
    VIM = 'D:\Vim\gvim_8.0.0027_x64'
    VIMRUNTIME = 'D:\Vim\gvim_8.0.0027_x64'
[vader-vim-800027-buf]
    command = 'D:\Vim\gvim_8.0.0027_x64\vim.exe'
    args = ['-Nu', 'test/vimrc', '-c', 'Vader! ${relativeFile}']
    isBackground = false
[vader-vim-800027-buf.options.env]
    VIM = 'D:\Vim\gvim_8.0.0027_x64'
    VIMRUNTIME = 'D:\Vim\gvim_8.0.0027_x64'
# vim 9.1.0196
[vader-vim-910196]
    command = "make"
    args = ['test']
    isBackground = false
[vader-vim-910196.options.env]
    VIM_BIN = 'D:\Vim\gvim_9.1.0196_x64\vim.exe'
    VIM_Es = "-Es"
    VIM = 'D:\Vim\gvim_9.1.0196_x64'
    VIMRUNTIME = 'D:\Vim\gvim_9.1.0196_x64'
[vader-vim-910196-buf]
    command = 'D:\Vim\gvim_9.1.0196_x64\vim.exe'
    args = ['-Nu', 'test/vimrc', '-Es', '-c', 'Vader! ${relativeFile}']
    isBackground = false
[vader-vim-910196-buf.options.env]
    VIM = 'D:\Vim\gvim_9.1.0196_x64'
    VIMRUNTIME = 'D:\Vim\gvim_9.0.0196_x64'
[vader-nvim-buf]
    command = 'nvim'
    args = ['-Nu', 'test/vimrc', '--headless', '-c', 'Vader! ${relativeFile}']
    isBackground = false
[vader-nvim-buf.options.env]
    VIM = ''
    VIMRUNTIME = ''
[generate-vim-doc]
    command = "python"
    args = ['-m', 'vimdoc', '.']
    isBackground = true
[test_problemMatcher]
    command = "echo"
    args = ['.SpaceVim.d/tasks.toml:6:1 test error message']
    isBackground = true
[test_problemMatcher.problemMatcher]
    useStdout = true
    errorformat = '%f:%l:%c\ %m'
[test_regexp]
    command = "echo"
    args = ['.SpaceVim.d/tasks.toml:12:1 test error message']
    isBackground = true
[test_regexp.problemMatcher]
    useStdout = true
[test_regexp.problemMatcher.pattern]
      regexp = '\(.*\):\(\d\+\):\(\d\+\)\s\(\S.*\)'
      file = 1
      line = 2
      column = 3
      #severity = 4
      message = 4
